version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.example
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run start:dev"
    networks:
      - hlab

  database:
    image: postgres:16-alpine
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    networks:
      - hlab

volumes:
  cache:
    driver: local
  db:
    driver: local
networks:
  hlab:
    name: hlab
    driver: bridge
